name: CI

on:
  push:
    branches: [ mainnet, bera, testnet ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm i --force

    - name: Set project name and environment
      id: set-project
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/mainnet' ]]; then
          echo "project_name=browndex-webswap-mainnet" >> $GITHUB_OUTPUT
          echo "ENV=mainnet" >> $GITHUB_ENV
        elif [[ ${{ github.ref }} == 'refs/heads/bera' ]]; then
          echo "project_name=browndex-webswap-bera" >> $GITHUB_OUTPUT
          echo "ENV=bera" >> $GITHUB_ENV
        elif [[ ${{ github.ref }} == 'refs/heads/testnet' ]]; then
          echo "project_name=browndex-webswap-testnet" >> $GITHUB_OUTPUT
          echo "ENV=testnet" >> $GITHUB_ENV
        fi

    - name: Build static site
      run: npm run build
      env:
        CI: false
        # Your build script can now access the ENV variable
        # For example, if using Create React App, you might name it REACT_APP_ENV
        REACT_APP_ENV: ${{ env.ENV }}

    - name: Deploy to Cloudflare Pages
      run: |
        npx --yes wrangler pages publish build/ --project-name=${{ steps.set-project.outputs.project_name }}
      env:
        CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}